package com.mycompany.bankingsystem;

import javax.swing.JOptionPane;

public class AiUi extends javax.swing.JFrame {
    int accId;
    boolean aiFrame;
    udashboard parent;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AiUi.class.getName());

    //temporary user
    public static String user = "Maju";
    public static String posit = "Admin";

    public javax.swing.JTextArea getChatBoxTextArea() {
        return ChatBoxTextArea;
    }

    public void setChatBoxTextAreaText(String text) {
        ChatBoxTextArea.setText(text);
    }

    public void appendChatBox(String text) {
        ChatBoxTextArea.append(text);
    }

    public AiUi() {
        initComponents();
        setLocationRelativeTo(null);
        ChatBoxTextArea.setEditable(false);
        ChatBoxTextArea.setLineWrap(true);
        ChatBoxTextArea.setWrapStyleWord(true);
        UserInputTextField.requestFocusInWindow();
        setVisible(true);
    }
    public AiUi(int id, boolean ai) {
        initComponents();
        setLocationRelativeTo(null);
        ChatBoxTextArea.setEditable(false);
        ChatBoxTextArea.setLineWrap(true);
        ChatBoxTextArea.setWrapStyleWord(true);
        UserInputTextField.requestFocusInWindow();
        setVisible(true);
        aiFrame = ai;
    }
    public AiUi(int id, boolean ai, udashboard parentFrame) {
        initComponents();
        this.parent = parentFrame;
        accId = id;
        aiFrame = ai;

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AiTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatBoxTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        UserInputTextField = new javax.swing.JTextField();
        InputBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jPanel1.setBackground(new java.awt.Color(133, 14, 53));

        AiTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AiTitle.setForeground(new java.awt.Color(252, 245, 238));
        AiTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AiTitle.setText("AI ASSISSTANT");

        ChatBoxTextArea.setColumns(20);
        ChatBoxTextArea.setForeground(new java.awt.Color(133, 14, 53));
        ChatBoxTextArea.setRows(5);
        ChatBoxTextArea.setText("AI: Hi! how can I help you today?");
        ChatBoxTextArea.setMargin(new java.awt.Insets(6, 10, 6, 10));
        jScrollPane1.setViewportView(ChatBoxTextArea);

        jLabel1.setForeground(new java.awt.Color(252, 245, 238));
        jLabel1.setText("Write your response here");

        UserInputTextField.setForeground(new java.awt.Color(133, 14, 53));

        InputBtn.setBackground(new java.awt.Color(255, 196, 196));
        InputBtn.setForeground(new java.awt.Color(133, 14, 53));
        InputBtn.setText("Enter");
        InputBtn.addActionListener(this::InputBtnActionPerformed);

        closeBtn.setBackground(new java.awt.Color(255, 196, 196));
        closeBtn.setForeground(new java.awt.Color(133, 14, 53));
        closeBtn.setText("Close");
        closeBtn.addActionListener(this::closeBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(closeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserInputTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(InputBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBtnActionPerformed
        String userText = UserInputTextField.getText().trim();

        if (userText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field cannot be empty!");
            return;
        }

        // show user message
        ChatBoxTextArea.append("\n" + user + ": " + userText);
        UserInputTextField.setText("");

        try {

            // call AI
            String response = OllamaService.askAI(userText);
            String finalResponse = AiFunction.parse(response, this);

        } catch (Exception e) {
            ChatBoxTextArea.append("\nAI: Error connecting to AI");
            e.printStackTrace();
        }

        ChatBoxTextArea.setCaretPosition(ChatBoxTextArea.getDocument().getLength());
        UserInputTextField.requestFocusInWindow();
    }//GEN-LAST:event_InputBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
        
        parent.setVisible(true);
        
        
        
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AiUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AiTitle;
    private javax.swing.JTextArea ChatBoxTextArea;
    private javax.swing.JButton InputBtn;
    private javax.swing.JTextField UserInputTextField;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
